[package]
name = "integration_test"
version = "0.1.0"
authors = ["Steven Roose <steven@stevenroose.org>"]

[dependencies]
bitcoincore-rpc = { path = "../client" }
bitcoin = { version = "0.26", features = [ "use-serde", "rand" ], git = "http://github.com/tcharding/rust-bitcoin", branch = "dogecoin" }
lazy_static = "1.4.0"
log = "0.4"
